### ISSUE TITLE
Delete My Garage Items

### ISSUE THREAD

**Issue by olamide87** [olamide87/myGarage#13]

**Comment by olamide87** [comment]
User Story
As a user, when I Click the Delete Garage item button it should be deleted and I should no longer should see that item .

AC
WHEN the user clicks delete button on a Garage Item card,
THEN I should see the item dissapear

Dev Notes
TODO:
create axios delete function
need to have remaining items on the page reprint after delete event takes place.

**Comment by mtgill** [comment]
You'll probably need to add something about updating the page with the remaining items after the delete runs
