### ISSUE TITLE
add Garage item

### ISSUE THREAD

**Issue by olamide87** [olamide87/myGarage#14]

**Comment by olamide87** [comment]
User Story
As a user, when I click the add new garage item button a new garage item form should load onto the page.

AC
WHEN the user clicks the new garage item button
THEN I should see a new garage item form
AND there should be a form to select garage item name, Image Url, isCheckout?, checkout date, contact

Dev Notes
TODO:
Get add Category data, for each add options for new garage item.
When form is submitted will need to create a function that will grab garageitemID, and create an new object, and reprint it to the page.
need to create axios post call in garageItemData.js this will allow a new garageItem object to be added to firebase

![image](https://user-images.githubusercontent.com/59629698/93154031-3ddce400-f6c8-11ea-9fb9-6437d46083f5.png)

**Comment by mtgill** [comment]
Missing information about POST action to add the new item to firebase
