### ISSUE TITLE
edit My Garage item

### ISSUE THREAD

**Issue by olamide87** [olamide87/myGarage#16]

**Comment by olamide87** [comment]
## User Story
As a user, I need to be able to edit my Garage item after they have been created.

## AC
WHEN the user is on a single my Garage item page 
THEN then they should see all of their garag items
AND and each should have an edit button
AND when the edit button is clicked, a form should display with all of the existing data pre-populated
AND when the user makes a change and saves it, they should then see the new data displayed on the page

## Dev Notes
Create an axios put call to update the garage item 
this should allow the new data to update in firebase
also need to have page reprint new edited Garage Item and unedited garage items

**Comment by mtgill** [comment]
So far so good but you'll probably need to add additional dev notes about updating the page after the edit runs, similar to https://github.com/olamide87/myGarage/issues/13
