### ISSUE TITLE
Edit Garage Category

### ISSUE THREAD

**Issue by olamide87** [olamide87/myGarage#6]

**Comment by olamide87** [comment]
## User Stories
As a user, when I navigate to a single view Garage Category  I should see an Edit button.

As a user, when I click the Edit button on a single view page, I should be directed  to the  /edit endpoint which makes the editable fields into text boxes.

As a user, if I've already clicked the Edit button, the text on the Edit Button should change to Save. Clicking on this button will submit the form fields as an update for the respective single view item.

## AC
When clicking the Save button, this should display the newly edited garage category. 
## Dev Notes
Create an axios put call to update the garage Category
this should allow the new data to update in firebase
also need to have page reprint new edited Garage Category and unedited garage categories

**Comment by mtgill** [comment]
Missing dev notes
