### ISSUE TITLE
Delete Gargage Category

### ISSUE THREAD

**Issue by olamide87** [olamide87/myGarage#7]

**Comment by olamide87** [comment]
## User Story
As a user, when I Click the Delete Category button it should be deleted and I should no longer should see that category .

## AC
WHEN the user clicks delete button on a category card,
THEN I should see the category dissapear


## Dev Notes
TODO:
create axios delete function 
need to reprint remaining Garage categories after delete Category event

**Comment by mtgill** [comment]
Same issue as https://github.com/olamide87/myGarage/issues/13, need more information about updating the page with remaining items
