### ISSUE TITLE
Add Garage Category

### ISSUE THREAD

**Issue by olamide87** [olamide87/myGarage#9]

**Comment by olamide87** [comment]
## User Story
As a user, when I click the add new category button a new category form should load into the main console.

## AC
WHEN the user clicks the new category button
THEN I should see a new category form
AND there should be a form to select Category Name and Image Url

## Dev Notes
TODO:
Get add Category data, for each add options for new category.
When form is submitted will need to create a function that will  grab categoryID, and create an new  object, and reprint it to the page.
*Create axios post function to add new object in firbase this function will live in garageCategoryData.js 

![image](https://user-images.githubusercontent.com/59629698/93049632-0407d100-f627-11ea-9c25-ddfc75749d9f.png)

**Comment by mtgill** [comment]
Dev notes missing where/how you'll use POST for this add action
